### PR TITLE
WIP: add scroll functionality

### PR DESCRIPTION
**Pull request by alavendelm**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Just to be clear, this is WIP?

**Comment by alavendelm** [comment]
yes. I've added the scripts and it's not working yet. Maybe you can see what i'm missing.

**Comment by ChrisRackauckas** [comment]
Just edited the title. It's common to note it's still in progress with a `WIP:`.

**Comment by alavendelm** [comment]
yeap sure. I had no idea what WIP was. had to google it.

**Comment by ChrisRackauckas** [comment]
It just helps to make sure I don't accidentally merge when cleaning up some repos. I'll take a look at this when I find the time, but right now I'm cramming to finish for my presentation.

**Comment by ChrisRackauckas** [comment]
That update was added to this PR branch. Was that intentional?

**Comment by ChrisRackauckas** [comment]
Do you want me to cherrypick that last commit?

**Comment by alavendelm** [comment]
Hi--- yes I would like today's commits to go through without the rest of this PR.

I suppose really (and for future) I should move this PR (the scroll functionality) off master? Is this straightforward?

**Comment by ChrisRackauckas** [comment]
>Hi--- yes I would like today's commits to go through without the rest of this PR.

Alright, I cherrypicked and added that commit to master.

>I suppose really (and for future) I should move this PR (the scroll functionality) off master? Is this straightforward?

Yes, I would recommend never working directly on master. What you can do is branch it where it is, close this PR (open a new one), reset local master to origin/master, then force push master to your fork. These days I suggest GitKraken to make this stuff easier since it's all point and click.

BTW, a video I just put out which doesn't show exactly this, but similar stuff, is here:

https://www.youtube.com/watch?v=tx8DRc7_c9I

**Pull request closed without merging**
