### PR TITLE
no video branch (try again)

### PR DESCRIPTION
**Pull request by alavendelm**

### CODE REVIEW

**Comment by alavendelm** [comment]
still not sure. done right?!

**Comment by ChrisRackauckas** [comment]
Very close. Reset once more to get rid of the `reset to before vid`. It's hiding some of the binaries in DS_STORE.

**Comment by ChrisRackauckas** [comment]
So reset head and force push. Then it should be good

**Comment by ChrisRackauckas** [comment]
Note you don't have to create a new PR.

**Comment by alavendelm** [comment]
ok, now?

**Comment by ChrisRackauckas** [comment]
There shouldn't be a commit `fix DS_Store`. You need to unstage the changes rather than committing and pushing. Try using

```
git reset --hard
```

then doing a force push.

**Comment by alavendelm** [comment]
ok I did git reset --hard <"edit posts" commit>

**Comment by alavendelm** [comment]
yay, we got there. ;)

**Pull request merged**
