### PR TITLE
branched (no video)

### PR DESCRIPTION
**Pull request by alavendelm**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
This still has the video hosting commit in there.

**Comment by ChrisRackauckas** [comment]
Do

```
git revert HEAD~
```

twice, and then submit that PR. It should just have the commits `update imgs` and `edit posts`. Then handle the videos in another.

**Comment by alavendelm** [comment]
Right. I can't use gitkraken properly (yet) then.

**Comment by ChrisRackauckas** [comment]
Sorry, reset, not revert.

**Comment by alavendelm** [comment]
I did git reset HEAD~ twice, but then do I need to force push to remote master (which is ahead)?

**Comment by ChrisRackauckas** [comment]
yes, you need to force push.

**Pull request closed without merging**
